name: Build and Test Zephyr Application

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build Zephyr Application
    runs-on: ubuntu-latest
    container: ghcr.io/mistywest/zephyr-base:amd64

    strategy:
      matrix:
        board: [nrf52840dk/nrf52840, nucleo_f401re]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Initialize West
        run: |
          west init -l .
          west update
          west zephyr-export

      - name: Build Application for ${{ matrix.board }}
        run: |
          west build -b ${{ matrix.board }} --pristine always -d build_${{ matrix.board }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware_${{ matrix.board }}
          path: build_${{ matrix.board }}/zephyr/*.bin

  test:
    name: Run Twister Tests with Coverage
    runs-on: ubuntu-latest
    container: ghcr.io/mistywest/zephyr-base:amd64
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Initialize West
        run: |
          west init -l .
          west update
          west zephyr-export

      - name: Run Twister Tests with Coverage
        run: |
          west twister --coverage -p native_sim --outdir twister_output

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: twister_test_coverage
          path: twister_output/coverage/